---
title: "Participate in a Study"
---

## Do you speak Spanish?

We are recruiting participants for an EEG study on how Spanish speakers process
language in real time. If you are interested, we would love to hear from you.

### What

An EEG (electroencephalography) study to learn more about how Spanish speakers
process language in real time. Participants complete a listening task while
wearing an EEG cap. You will be at the lab for approximately 1 hour 30 minutes
to 2 hours.

### Who

Native Spanish speakers and second-language speakers of Spanish, ages 18 to 40.

### Where

Bilingualism: Language in NeuroKognition (BLiNK) Lab<br>
1 Spring Street, New Brunswick, NJ 08901

### Pay

Participants receive $30 per hour for completing the study.

### How to Participate

[**Sign up here**](https://docs.google.com/forms/d/e/1FAIpQLSeHEQJmbdqIRUuXQhm3bDJ4Bp71mEE1UlRlqFscCG3TZIHNFw/viewform){.signup-button}

<p style="font-size: 0.85em; color: #777; margin-top: 2em;">
This study has been approved by the Rutgers University Institutional Review
Board. Study ID: Pro2023001581.
</p>
